import {pyBasic, pyAdvance, pyComplete} from './images';

const COURSES = [
    {
        'title' : 'Python Foundation - Live',
        'hours' : '15+',
        'image' : pyBasic,
        'description' : 'Python foundation course first step to you career in Web development, AI/ML and Devops.',
        'video': 'https://www.youtube.com/embed/Lop3KwJ5DZ0',
        'content': [
            '01. Overview',
            '02. Setup',
            '03. Syntax',
            '04. Variables & Operators',
            '05. String',
            '06. List, List Comprehentions',
            '07. Tuple',
            '08. Set',
            '09. Dictionary',
            '10. Control Flow',
            '11. Functions',
            '12. IO, Files',
            '13. Exception Handling',
            '14. Modules, Built-in Modules',
            '15. Logging, Debugging',
        ],
        'price': '5999',
        'url' : '/learn-python-basics-live',
        'join': 'https://t.me/+KBxZKPvNjPFkNjg1'
    },
    {
        'title' : 'Python Advance - Live',
        'hours' : '12+',
        'image' : pyAdvance,
        'description' : 'Ace your career with Python Advance concepts, know better than your colleague.',
        'video': 'https://www.youtube.com/embed/Lop3KwJ5DZ0',
        'content': [
            '01. Regular Expression',
            '02. Object Oriented Programming-1',
            '03. Object Oriented Programming-2',
            '04. Object Oriented Programming-3',
            '05. Functional Programming: Map, Filter, Reduce',
            '06. Advance Functions',
            '07. Collections',
            '08. Pickle',
            '09. Design Patterns',
            '10. Concurrency Multi-Threading',
            '11. Concurrency Multi-Processing',
            '12. Concurrency Async',
            '13. DB, Email Integrations',
            '14. PIP Package Creation',
        ],
        'price': '6999',
        'url' : '/learn-python-advance-live',
        'join': 'https://t.me/+KBxZKPvNjPFkNjg1'
    },
    {
        'title' : 'Complete Python - Live',
        'hours' : '31+',
        'image' : pyComplete,
        'description' : 'Learn Python from Basics to Advnace, become an expert Python Developer needed by many top IT companies',
        'video': 'https://www.youtube.com/embed/Lop3KwJ5DZ0',
        'content': [
            '01. Overview',
            '02. Setup',
            '03. Syntax',
            '04. Variables & Operators',
            '05. String',
            '06. List, List Comprehentions',
            '07. Tuple',
            '08. Set',
            '09. Dictionary',
            '10. Control Flow',
            '11. Functions',
            '12. IO, Files',
            '13. Exception Handling',
            '14. Modules, Built-in Modules',
            '15. Logging, Debugging',
            '16. Regular Expression',
            '17. Object Oriented Programming-1',
            '18. Object Oriented Programming-2',
            '19. Object Oriented Programming-3',
            '20. Functional Programming: Map, Filter, Reduce',
            '21. Advance Functions',
            '22. Collections',
            '23. Pickle',
            '24. Design Patterns',
            '25. Concurrency Multi-Threading',
            '26. Concurrency Multi-Processing',
            '27. Concurrency Async',
            '28. DB, Email Integrations',
            '29. PIP Package Creation',
            '30. Elective - Python Django Intro (Any One)',
            '30. Elective - Data Science Intro (Any One)',
            '30. Elective - DevOps Intro (Any One)',
            '31. Interview Prep: Coding Patterns',
            
        ],
        'price': '9999',
        'url' : '/learn-python-complete-live',
        'join': 'https://t.me/+KBxZKPvNjPFkNjg1'
    },
    
];

export default COURSES;